'use client'
import { useEffect, useMemo, useState } from 'react'
import { Check, Search, Tag } from 'lucide-react'

type TagColor='gray'|'red'|'orange'|'yellow'|'green'|'blue'|'purple'|'pink'
type TagItem={id:string;name:string;color:TagColor}
type Assignment={conversation_id:string;tag_id:string}
const palette:TagColor[]=['gray','red','orange','yellow','green','blue','purple','pink']

export function TagManager({conversationId,agentId,compact=false,onChanged}:{conversationId?:string;agentId?:string;compact?:boolean;onChanged?:()=>void}){
 const [tags,setTags]=useState<TagItem[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[query,setQuery]=useState(''),[name,setName]=useState(''),[color,setColor]=useState<TagColor>('gray'),[editing,setEditing]=useState<TagItem|null>(null),[error,setError]=useState(''),[busyId,setBusyId]=useState<string|null>(null)
 const load=async()=>{const r=await fetch(`/api/tags${conversationId?`?conversationId=${encodeURIComponent(conversationId)}`:''}`,{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'Tags unavailable');setTags(p.tags??[]);setAssignments(p.assignments??[])}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[conversationId])
 const assigned=new Set(assignments.map(a=>a.tag_id));const visible=useMemo(()=>tags.filter(t=>t.name.toLowerCase().includes(query.toLowerCase())),[tags,query])
 const save=async()=>{if(!name.trim())return;setError('');const r=await fetch('/api/tags',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{id:editing.id,name,color}:{name,color,agentId})});const p=await r.json();if(!r.ok){setError(p.error||'Could not save tag');return}setName('');setColor('gray');setEditing(null);await load();onChanged?.()}
 const removeTag=async(id:string)=>{if(!confirm('Delete this tag? It will be removed from every conversation.'))return;setBusyId(id);try{const r=await fetch('/api/tags',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(!r.ok)throw new Error('Could not delete tag');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Could not delete tag')}finally{setBusyId(null)}}
 const toggle=async(tagId:string)=>{if(!conversationId)return;const isAssigned=assigned.has(tagId);setBusyId(tagId);setError('');try{const r=await fetch('/api/tags',{method:isAssigned?'DELETE':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversationId,tagId,agentId})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||'Could not update conversation tag');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Could not update conversation tag')}finally{setBusyId(null)}}
 return <div className={`tag-manager ${compact?'tag-manager-compact':''}`}>
 {!compact&&<><div className="tag-manager-title"><div><h2>Tags</h2><p>Create reusable labels and choose a color for each one.</p></div></div><div className="tag-create-row"><input value={name} onChange={e=>setName(e.target.value)} placeholder={editing?'Edit tag name':'New tag name'} onKeyDown={e=>{if(e.key==='Enter')void save()}}/><div className="tag-color-picker" aria-label="Tag color">{palette.map(c=><button key={c} type="button" title={c} className={`tag-color-dot tag-color-${c} ${color===c?'selected':''}`} onClick={()=>setColor(c)}/>)}</div><button className="primary-small" onClick={()=>void save()}>{editing?'Update tag':'+ New tag'}</button>{editing&&<button className="secondary-small" onClick={()=>{setEditing(null);setName('');setColor('gray')}}>Cancel</button>}</div></>}
 <div className="tag-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tags..."/></div>{conversationId&&<p className="tag-assignment-help">Click a tag to add it to this conversation. Click it again to remove it.</p>}{error&&<p className="form-error">{error}</p>}
 <div className="tag-list">{visible.length===0?<p className="muted-copy">No tags found.</p>:visible.map(item=><div className="tag-row" key={item.id}><button type="button" disabled={busyId===item.id} data-color={item.color||'gray'} className={`tag-pill tag-pill-${item.color||'gray'} ${assigned.has(item.id)?'tag-pill-active':''} ${conversationId?'tag-pill-clickable':''}`} onClick={()=>conversationId?void toggle(item.id):undefined}><Tag size={13}/><span>{item.name}</span>{conversationId&&assigned.has(item.id)&&<Check size={13}/>}</button>{!compact&&<div className="tag-row-actions"><button type="button" onClick={()=>{setEditing(item);setName(item.name);setColor(item.color||'gray')}}>Edit</button><button type="button" className="danger-text" disabled={busyId===item.id} onClick={()=>void removeTag(item.id)}>Delete</button></div>}</div>)}</div></div>
}
